name: CD

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node js
        uses: actions/setup-node@v3
        with:
          node-version: 18.20.2
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - run: npm install
      - name: Deploy
        run: npm run build
