name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.20.2
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - run: npm install

      - name: Linting
        run: npm run lint

      - name: Tests
        run: npm test
